import React,{useState,useEffect} from 'react';
import {Icon,Header,Metrics,Panel,Button,Badge,Tag,Tabs,Search,Drawer,Code,Empty,StatusPill,useResource,ErrorNotice,ExecutionTable,ArtifactList,Preview,StatBar} from './common.jsx';
import {request,newId,short,formatTime,terminal} from './api.js';
const BASE='/api/automation';
const template=channel=>channel==='API'?{version:2,target:'api:todo-demo',steps:[{op:'request',target:'GET',value:'{"path":"/api/products"}'},{op:'assertStatus',target:'response',value:'200'},{op:'assertJson',target:'$.total',value:'3'}]}:{version:2,target:'web:todo-demo',steps:[{op:'fill',target:'testId:title',value:'Prepare interview'},{op:'click',target:'testId:add',value:null},{op:'assertText',target:'testId:items',value:'Prepare interview'}]};
export function RunDetail({id,token,onClose,sandbox=false}){
 const base=sandbox?'/api/sandbox':BASE;const resource=useResource(`${base}/${sandbox?'console/executions':'runs'}/${id}`,token,2000);const row=resource.data;
 const [tab,setTab]=useState('result'),[artifact,setArtifact]=useState(null),[error,setError]=useState('');
 const report=row?.result?.report;const result=row?.result||{};
 const preview=name=>setArtifact({taskId:id,name});
 return <><Drawer title={row?.title||`Execution ${short(id)}`} subtitle={sandbox?'SANDBOX / EXECUTION':'AUTOMATION / EXECUTION'} onClose={onClose} wide actions={<><Button icon="refresh" onClick={resource.refresh}>刷新</Button>{row&&!terminal(row.status)&&<Button danger onClick={async()=>{try{await request(`${base}/${sandbox?'executions':'runs'}/${id}/cancel`,token,{method:'POST',body:{}});resource.refresh();}catch(e){setError(e.message);}}}>取消执行</Button>}<Button onClick={onClose}>关闭</Button></>}>
 <ErrorNotice error={resource.error||error}/>{row&&<><div className="detail-facts"><div><label>执行状态</label><Badge value={row.status}/></div><div><label>执行类型</label><StatusPill channel={report?.channel||row.channel}/></div><div><label>发起时间</label><b>{formatTime(row.createdAt)}</b></div><div><label>Run ID</label><code>{short(row.id)}</code></div><div><label>总耗时</label><b>{(row.durationMs/1000).toFixed(1)} s</b></div><div><label>{sandbox?'容器清理':'模型模式'}</label>{sandbox?<Badge value={row.cleanupStatus}/>:<b>{result.providerMode==='not-used'?'无需模型':result.providerMode||'等待结果'}</b>}</div></div>
 <Tabs value={tab} onChange={setTab} items={[{id:'result',label:'执行报告'},{id:'input',label:'输入与流程'},{id:'provenance',label:'版本与来源'}]}/>
 {row.error&&<div className="notice error"><Icon name="alert"/>{row.error}</div>}{!terminal(row.status)&&<div className="progress"><span className="spinner"/>任务正在后台执行，记录每两秒自动刷新。</div>}
 {tab==='result'&&<><div className="artifact-chips">{(result.artifacts||[]).map(name=><Button key={name} icon="file" onClick={()=>preview(name)}>{name}</Button>)}{sandbox&&report?.channel==='WEB'&&<Button icon="eye" onClick={()=>preview('screenshot.png')}>浏览器截图</Button>}</div>{report?<><Panel title={report.passed?'所有断言通过':'执行未通过'} description={`${report.steps?.length||0} 个已执行步骤 · ${report.syntheticTarget?'隔离示例环境':'注册目标环境'} · ${report.durationMs||0} ms`}><div className="step-list">{report.steps?.map((step,i)=><div className="step-item" key={i}><span className="step-num">{String(i+1).padStart(2,'0')}</span><div><strong>{step.op} {step.target&&<code>· {step.target}</code>}</strong><p>{step.error||`${step.durationMs||0} ms`}</p>{step.http&&<details><summary>HTTP {step.http.status} · {step.http.method} {step.http.path}</summary><Code label="RESPONSE" value={step.http.body}/></details>}</div><Badge value={step.passed?'SUCCEEDED':'FAILED'}/></div>)}</div></Panel>{!sandbox&&row.remoteId&&<Button icon="box" onClick={()=>window.location.assign(`/sandbox/#/executions/${row.remoteId}`)}>查看 Sandbox 执行与截图</Button>}</>:terminal(row.status)?<Empty title="没有可展示的断言报告" description={row.error||'请查看输入和执行状态。'}/>:null}</>}
 {tab==='input'&&<Code label="RUN INPUT" value={row.input}/>}
 {tab==='provenance'&&<Code label="PROVENANCE" value={{id:row.id,attemptId:row.attemptId,executionId:row.remoteId,compilerVersion:result.compilerVersion,workflowHash:result.workflowHash,specHash:result.specHash,repository:result.repository,workspaceId:result.workspaceId,modelRequestId:result.modelRequestId}}/>}
 </>}</Drawer>{artifact&&<Preview artifact={artifact} base={base} token={token} onClose={()=>setArtifact(null)}/>}</>;
}
function CaseEditor({asset,token,onClose,onSaved}){
 const [title,setTitle]=useState(asset?.title||''),[description,setDescription]=useState(asset?.description||''),[channel,setChannel]=useState(asset?.channel||'WEB'),[text,setText]=useState(JSON.stringify(asset?.workflow||template('WEB'),null,2));const [error,setError]=useState(''),[busy,setBusy]=useState(false),[compiled,setCompiled]=useState(null);
 async function save(){setBusy(true);try{const result=await request(`${BASE}/cases${asset?'/'+asset.id:''}`,token,{method:asset?'PUT':'POST',body:{title,description,workflow:JSON.parse(text),tags:asset?.tags||['P1'],revision:asset?.revision}});onSaved(result);onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Drawer title={asset?'编辑用例':'创建自动化用例'} subtitle="CASE / VERSIONED WORKFLOW" onClose={onClose} wide actions={<><Button onClick={onClose}>取消</Button><Button icon="code" onClick={async()=>{try{setCompiled(await request(`${BASE}/compile`,token,{method:'POST',body:JSON.parse(text)}));setError('');}catch(e){setError(e.message);}}}>校验并编译</Button><Button primary icon="check" loading={busy} onClick={save}>保存{asset?'新版本':'用例'}</Button></>}>
 <ErrorNotice error={error}/><div className="form-grid"><label className="field">用例名称<input value={title} maxLength={160} onChange={e=>setTitle(e.target.value)} placeholder="例如：购物车金额计算"/></label><label className="field">执行类型<select value={channel} onChange={e=>{setChannel(e.target.value);setText(JSON.stringify(template(e.target.value),null,2));}}><option>WEB</option><option>API</option></select></label><label className="field full">说明<textarea rows={2} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="field full">Workflow JSON<textarea className="mono" rows={18} value={text} onChange={e=>setText(e.target.value)} spellCheck={false}/><small>Web 支持定位、输入、点击、导航与断言；API 支持 HTTP 请求、状态码、JSON 和响应断言。目标使用服务端注册的 Profile。</small></label></div>{compiled&&<Code label={`SPEC / ${compiled.compilerVersion}`} value={compiled.spec}/>}</Drawer>;
}
function CaseDetail({asset,token,onClose,onEdit,onRun}){const [tab,setTab]=useState('workflow');const versions=useResource(`${BASE}/cases/${asset.id}/versions`,token);const [compiled,setCompiled]=useState(null),[error,setError]=useState('');useEffect(()=>{request(`${BASE}/compile`,token,{method:'POST',body:asset.workflow}).then(setCompiled).catch(e=>setError(e.message));},[asset,token]);return <Drawer title={asset.title} subtitle={`CASE / ${asset.channel} / V${asset.revision}`} onClose={onClose} wide actions={<><Button icon="code" onClick={()=>onEdit(asset)}>编辑用例</Button><Button primary icon="play" onClick={()=>onRun(asset)}>立即执行</Button></>}><ErrorNotice error={error}/><div className="detail-facts"><div><label>类型</label><StatusPill channel={asset.channel}/></div><div><label>当前版本</label><b>v{asset.revision}</b></div><div><label>数据来源</label><b>{asset.demo?'可执行示例用例':'用户创建'}</b></div></div><p className="muted" style={{fontSize:12,lineHeight:1.8,marginBottom:20}}>{asset.description}</p><Tabs value={tab} onChange={setTab} items={[{id:'workflow',label:'Workflow'},{id:'code',label:'编译产物'},{id:'versions',label:'版本记录'}]}/>{tab==='workflow'&&<><div className="section-heading">{asset.workflow.steps.length} 个操作与断言 · {asset.workflow.target}</div><div className="step-list">{asset.workflow.steps.map((s,i)=><div className="step-item" key={i}><span className="step-num">{String(i+1).padStart(2,'0')}</span><div><strong>{s.op} <code>{s.target}</code></strong><p>{s.value}</p></div><Tag color={s.op.startsWith('assert')?'green':'blue'}>{s.op.startsWith('assert')?'断言':'操作'}</Tag></div>)}</div></>}{tab==='code'&&<><Code label={`SPEC / ${compiled?.compilerVersion||''}`} value={compiled?.spec||'编译中…'}/><div className="notice">确定性编译 · 相同 Workflow 与编译器版本产生相同 Spec Hash。</div></>}{tab==='versions'&&<div className="timeline">{versions.data?.map(v=><div className="timeline-item" key={v.revision}><span className="timeline-dot"/><div><b>版本 v{v.revision}</b><p className="mono">{v.workflowHash.slice(0,24)}</p></div><time>{formatTime(v.createdAt)}</time></div>)}</div>}</Drawer>;}
export function AutomationViews({route,token,notify,navigate}){
 const cases=useResource(`${BASE}/cases`,token),runs=useResource(`${BASE}/runs`,token,5000),overview=useResource(`${BASE}/overview`,token,8000),artifacts=useResource(`${BASE}/artifacts`,token,8000);
 const [search,setSearch]=useState(''),[channel,setChannel]=useState('ALL'),[status,setStatus]=useState('ALL'),[selected,setSelected]=useState(null),[edit,setEdit]=useState(null),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false);
 const records=cases.data||[],history=runs.data||[],metrics=overview.data?.metrics||{};
 const activeRun=route.startsWith('runs/')?route.split('/')[1]:null;
 const filtered=records.filter(c=>(channel==='ALL'||c.channel===channel)&&(c.title+' '+c.id).toLowerCase().includes(search.toLowerCase()));
 const filteredRuns=history.filter(r=>(status==='ALL'||r.status===status)&&(r.title+' '+r.id).toLowerCase().includes(search.toLowerCase()));
 async function seed(){setBusy(true);try{const result=await request(`${BASE}/demo/seed`,token,{method:'POST',body:{}});cases.refresh();overview.refresh();notify(`已准备 ${result.created} 条演示用例`);}catch(e){notify(e.message);}finally{setBusy(false);}}
 async function run(asset){try{const j=await request(`${BASE}/cases/${asset.id}/run`,token,{method:'POST',body:{},key:newId()});setSelected(null);navigate('runs/'+j.id);runs.refresh();notify('执行任务已提交');}catch(e){notify(e.message);}}
 function rows(){return <><div className="toolbar"><Tabs value={channel} onChange={setChannel} items={[{id:'ALL',label:'全部用例',count:records.length},{id:'WEB',label:'Web 自动化',icon:'globe',count:records.filter(x=>x.channel==='WEB').length},{id:'API',label:'API 自动化',icon:'api',count:records.filter(x=>x.channel==='API').length}]}/><Search value={search} onChange={setSearch}/></div>{filtered.length?<div className="table-wrap"><table><thead><tr><th>用例名称</th><th>类型</th><th>标签</th><th>步骤</th><th>版本</th><th>更新于</th><th>操作</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td className="clickable" onClick={()=>setSelected(c)}><div className="title-cell"><span className={`row-icon ${c.channel==='API'?'purple':''}`}><Icon name={c.channel==='API'?'api':'globe'}/></span><div><strong>{c.title}</strong><small>{short(c.id)}{c.demo?' · DEMO':''}</small></div></div></td><td><StatusPill channel={c.channel}/></td><td>{c.tags?.slice(0,2).map(t=><Tag key={t} color={t==='P0'?'purple':'gray'}>{t}</Tag>)}</td><td>{c.workflow.steps.length} steps</td><td className="mono">v{c.revision}</td><td>{formatTime(c.updatedAt)}</td><td><div className="inline-actions"><Button icon="play" quiet onClick={()=>run(c)}>执行</Button><Button icon="eye" quiet onClick={()=>setSelected(c)}>详情</Button></div></td></tr>)}</tbody></table></div>:<Empty title="还没有匹配的用例" description="创建 Web/API 用例，或一键载入可执行的演示业务。"><Button primary icon="plus" onClick={()=>setEdit({create:true})}>创建用例</Button></Empty>}<div className="table-footer"><span>共 {filtered.length} 条 · 用例与执行记录独立保存</span><span>WORKFLOW V2</span></div></>;}
 return <><Header eyebrow="AUTOMATION WORKSPACE" title={route.startsWith('runs')?'执行记录':route==='artifacts'?'产物与存储':route==='cases'?'用例管理':'自动化概览'} description={route==='cases'?'统一管理 Web 与 API 自动化资产，让每一个用例都可编译、可执行、可追溯。':'从结构化用例到真实执行，让质量结论有据可查。'}><Button icon="refresh" onClick={()=>{cases.refresh();runs.refresh();overview.refresh();artifacts.refresh();}}>刷新</Button><Button primary icon="plus" onClick={()=>setEdit({create:true})}>创建用例</Button></Header><ErrorNotice error={cases.error||runs.error||overview.error}/>
 {records.length===0&&<div className="seed-banner"><div><strong>准备一个完整的演示工作区</strong><small>12 条 Web/API 用例，包括成功、边界与失败场景。执行记录由真实运行产生。</small></div><Button primary icon="spark" loading={busy} onClick={seed}>载入演示用例</Button></div>}
 {route==='overview'&&<><Metrics items={[{label:'自动化用例',value:records.length,note:`${overview.data?.webCases||0} Web / ${overview.data?.apiCases||0} API`,icon:'case'},{label:'执行总数',value:history.length,note:'当前账户真实执行记录',icon:'activity'},{label:'执行成功率',value:history.filter(x=>['SUCCEEDED','FAILED'].includes(x.status)).length?Math.round(history.filter(x=>x.status==='SUCCEEDED').length/history.filter(x=>['SUCCEEDED','FAILED'].includes(x.status)).length*100)+'%':'—',note:'已结束执行 · 不包含等待任务',icon:'shield',positive:true},{label:'已存储产物',value:artifacts.data?.length||0,note:overview.data?.storage?.backend==='supabase'?'Supabase 私有对象存储':overview.data?.storage?.backend,icon:'cloud'}]}/><div className="two-column"><Panel title="最近执行" description="编译版本、执行结果与容器状态完整关联" actions={<Button quiet icon="arrow" onClick={()=>navigate('runs')}>查看全部</Button>}><ExecutionTable rows={history.slice(0,5)} onOpen={id=>navigate('runs/'+id)}/></Panel><Panel title="用例覆盖分布" description="当前工作区资产"><div className="panel-body"><div className="summary-row"><span><i className="dot" style={{background:'#7f9bdd'}}/>Web 自动化</span><b>{records.filter(x=>x.channel==='WEB').length} 条</b></div><div className="summary-row"><span><i className="dot"/>API 自动化</span><b>{records.filter(x=>x.channel==='API').length} 条</b></div><div className="summary-row"><span><i className="dot" style={{background:'#62bd9e'}}/>已通过执行</span><b>{history.filter(x=>x.status==='SUCCEEDED').length} 次</b></div><div className="section-heading">执行结果分布</div><StatBar success={history.filter(x=>x.status==='SUCCEEDED').length} failed={history.filter(x=>x.status==='FAILED').length} other={history.filter(x=>!terminal(x.status)).length}/><p className="muted" style={{fontSize:10,lineHeight:1.9,marginTop:17}}>每次运行使用独立容器。用例、Workflow 和脚本版本保存在对象存储，可随时回溯。</p></div></Panel></div><Panel title="用例资产" actions={<Button quiet onClick={()=>navigate('cases')}>查看全部 →</Button>}>{rows()}</Panel></>}
 {route==='cases'&&<Panel title="全部用例" actions={<Button quiet icon="spark" loading={busy} onClick={seed}>补齐示例</Button>}>{rows()}</Panel>}
 {route.startsWith('runs')&&<Panel title="执行历史" description="真实运行记录 · 总耗时包含排队、编译与执行"><div className="toolbar"><Search value={search} onChange={setSearch}/><select aria-label="状态筛选" className="filter-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">全部状态</option><option value="SUCCEEDED">执行通过</option><option value="FAILED">执行失败</option><option value="RUNNING">执行中</option></select></div><ExecutionTable rows={filteredRuns} onOpen={id=>navigate('runs/'+id)}/></Panel>}
 {route==='artifacts'&&<><Metrics items={[{label:'产物总数',value:artifacts.data?.length||0,icon:'file'},{label:'存储后端',value:'Supabase',note:'Storage 私有 bucket',icon:'cloud'},{label:'访问方式',value:'鉴权下载',note:'归属校验后由服务端读取',icon:'shield'},{label:'版本校验',value:'SHA-256',note:'Workflow / Spec / Artifact',icon:'git'}]}/><Panel title="对象存储文件" description="Markdown、脚本、执行日志与报告"><ArtifactList rows={artifacts.data||[]} token={token} base={BASE} onPreview={setPreview}/></Panel></>}
 {selected&&<CaseDetail asset={selected} token={token} onClose={()=>setSelected(null)} onEdit={a=>{setSelected(null);setEdit(a);}} onRun={run}/>}{edit&&<CaseEditor asset={edit.create?null:edit} token={token} onClose={()=>setEdit(null)} onSaved={()=>{cases.refresh();overview.refresh();notify('用例已保存');}}/>}{activeRun&&<RunDetail id={activeRun} token={token} onClose={()=>navigate('runs')}/>}{preview&&<Preview artifact={preview} base={BASE} token={token} onClose={()=>setPreview(null)}/>}</>;
}
