import React,{useEffect,useState,useCallback} from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {request,short,formatTime,formatSize,download} from './api.js';
export function Icon({name='grid',size=18,...props}){const paths={grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z',layers:'m12 3 9 5-9 5-9-5zM3 12l9 5 9-5M3 16l9 5 9-5',case:'M8 3h8v4H8zM6 5H4v16h16V5h-2M8 11h8M8 15h6',activity:'M3 12h4l3-8 4 16 3-8h4',code:'m8 6-6 6 6 6M16 6l6 6-6 6M14 3l-4 18',box:'m12 2 9 5v10l-9 5-9-5V7zM3 7l9 5 9-5M12 12v10',cloud:'M6 18a5 5 0 1 1 0-10 7 7 0 0 1 13 1 4.5 4.5 0 0 1 0 9z',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',arrow:'M4 12h16m-6-6 6 6-6 6',plus:'M12 4v16M4 12h16',chevron:'m8 5 7 7-7 7',down:'m5 9 7 7 7-7',refresh:'M20 7V3l-4 4a8 8 0 1 0 3 10M20 3h-4',check:'m4 12 5 5L20 6',x:'m6 6 12 12M18 6 6 18',clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',file:'M14 2H5v20h14V7zM14 2v6h5M8 12h8M8 16h6',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6zM8 12l3 3 5-6',git:'M6 3v12a4 4 0 0 0 8 0V8M4 3h4M12 6h4M12 10h4',chart:'M4 20V10M10 20V4M16 20v-7M22 20H2',logout:'M9 3H3v18h6M8 12h13m-5-5 5 5-5 5',play:'m7 3 14 9-14 9z',api:'M5 4h14v16H5zM8 8h8M8 12h3M8 16h8',globe:'M2 12h20M12 2c6 6 6 14 0 20-6-6-6-14 0-20M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',alert:'m12 3 10 18H2zM12 9v5M12 17v1',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',copy:'M8 8h13v13H8zM16 8V3H3v13h5',terminal:'m4 6 6 6-6 6M13 18h7'};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}><path d={paths[name]||paths.grid}/></svg>;}
export const LABELS={SUCCEEDED:'执行通过',FAILED:'执行失败',RUNNING:'执行中',QUEUED:'排队中',CANCELLED:'已取消',TIMED_OUT:'超时',LOST:'待恢复',DRAFT:'草稿',DESTROYED:'已回收',PENDING:'待回收',confirmed_defect:'确认缺陷',needs_context:'待补上下文',no_issue:'已排除'};
export function Badge({value,children,tone}){return <span className={`badge tone-${tone||({SUCCEEDED:'green',FAILED:'red',TIMED_OUT:'red',LOST:'amber',RUNNING:'blue',QUEUED:'amber',DESTROYED:'green',confirmed_defect:'red',needs_context:'amber'}[value]||'gray')}`}><i/>{children||LABELS[value]||value}</span>;}
export function Tag({children,color='gray'}){return <span className={`tag ${color}`}>{children}</span>;}
export function Button({children,icon,primary,quiet,danger,loading,...props}){return <button className={`btn ${primary?'primary':''} ${quiet?'quiet':''} ${danger?'danger':''}`} disabled={loading||props.disabled} {...props}>{loading?<span className="spinner small"/>:icon&&<Icon name={icon} size={15}/>}<span>{children}</span></button>;}
export function Header({eyebrow,title,description,children}){return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div><div className="header-actions">{children}</div></div>;}
export function Metrics({items}){return <div className="metrics">{items.map((item,i)=><div className="metric" key={i}><div className="metric-label">{item.label}<Icon name={item.icon||'chart'} size={17}/></div><div className="metric-value">{item.value??'—'}<small>{item.unit}</small></div><div className={`metric-note ${item.positive?'positive':''}`}>{item.note||'来自当前账户的数据'}</div></div>)}</div>;}
export function Empty({title='暂无记录',description='完成一次操作后，结果会显示在这里。',children}){return <div className="empty"><div className="empty-icon"><Icon name="layers" size={25}/></div><h3>{title}</h3><p>{description}</p>{children}</div>;}
export function Panel({title,description,actions,children,className=''}){return <section className={`panel ${className}`}><div className="panel-head"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{actions}</div>{children}</section>;}
export function Tabs({items,value,onChange}){return <div className="tabs" role="tablist">{items.map(t=><button role="tab" aria-selected={value===t.id} className={value===t.id?'active':''} key={t.id} onClick={()=>onChange(t.id)}>{t.icon&&<Icon name={t.icon} size={15}/>} {t.label}{t.count!=null&&<span>{t.count}</span>}</button>)}</div>;}
export function Search({value,onChange,placeholder='搜索名称或 ID…'}){return <div className="search"><Icon name="search" size={16}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></div>;}
export function Drawer({title,subtitle,children,actions,onClose,wide}){useEffect(()=>{const f=e=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f);},[onClose]);return <div className="overlay" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section role="dialog" aria-modal="true" aria-label={title} className={`drawer ${wide?'wide':''}`}><header><div><span className="eyebrow">{subtitle||'DETAILS'}</span><h2>{title}</h2></div><button aria-label="关闭详情" className="icon-button" onClick={onClose}><Icon name="x"/></button></header><div className="drawer-body">{children}</div>{actions&&<footer>{actions}</footer>}</section></div>;}
export function MarkdownView({text}){return <div className="markdown"><Markdown remarkPlugins={[remarkGfm]}>{text||'*暂无输出*'}</Markdown></div>;}
export function Code({value,label='JSON'}){return <div className="code"><div>{label}<button onClick={()=>{navigator.clipboard?.writeText(typeof value==='string'?value:JSON.stringify(value,null,2));}}>复制</button></div><pre>{typeof value==='string'?value:JSON.stringify(value,null,2)}</pre></div>;}
export function useResource(path,token,interval=0){const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const refresh=useCallback(async()=>{if(!path||!token)return;try{const value=await request(path,token);setData(value);setError('');}catch(e){setError(e.message);}finally{setLoading(false);}},[path,token]);useEffect(()=>{setLoading(true);refresh();if(interval){const t=setInterval(refresh,interval);return()=>clearInterval(t);}},[refresh,interval]);return {data,error,loading,refresh,setData};}
export function ErrorNotice({error}){return error?<div className="notice error"><Icon name="alert"/>{error}</div>:null;}
export function StatusPill({channel}){return <span className={`type-pill ${channel==='API'?'api':'web'}`}><Icon name={channel==='API'?'api':'globe'} size={14}/>{channel||'WEB'}</span>;}
export function StatBar({success=0,failed=0,other=0}){const total=success+failed+other||1;return <div className="statbar"><span style={{width:`${success/total*100}%`,background:'#23aa83'}}/><span style={{width:`${failed/total*100}%`,background:'#ec7082'}}/><span style={{width:`${other/total*100}%`,background:'#9baac6'}}/></div>;}
export function ExecutionTable({rows=[],onOpen,showChannel=true}){return rows.length?<div className="table-wrap"><table><thead><tr><th>执行任务</th>{showChannel&&<th>类型</th>}<th>执行状态</th><th>总耗时</th><th>发起时间</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} onClick={()=>onOpen(row.id)} className="clickable"><td><div className="title-cell"><span className="row-icon"><Icon name={showChannel?'play':'box'} size={17}/></span><div><strong>{row.title||`Execution ${short(row.id)}`}</strong><small>{short(row.id)}{row.demo?' · 示例用例':''}</small></div></div></td>{showChannel&&<td><StatusPill channel={row.channel}/></td>}<td><Badge value={row.status}/></td><td className="mono">{row.durationMs?`${(row.durationMs/1000).toFixed(1)}s`:'—'}</td><td className="muted">{formatTime(row.createdAt)}</td><td><Icon name="chevron" size={15}/></td></tr>)}</tbody></table></div>:<Empty/>;}
export function ArtifactList({rows=[],token,base,onPreview}){return rows.length?<div className="table-wrap"><table><thead><tr><th>产物文件</th><th>存储后端</th><th>大小</th><th>写入时间</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.taskId+r.name}><td><div className="title-cell"><span className="row-icon purple"><Icon name="file"/></span><div><strong>{r.name}</strong><small>{short(r.taskId)} · SHA {r.sha256?.slice(0,10)}</small></div></div></td><td><Tag color="purple">{r.backend==='supabase'?'Supabase Storage':'Local'}</Tag></td><td className="mono">{formatSize(r.size)}</td><td>{formatTime(r.createdAt)}</td><td className="row-actions"><Button icon="eye" quiet onClick={()=>onPreview(r)}>预览</Button><Button icon="download" quiet onClick={()=>download(`${base}/artifacts/${r.taskId}/${r.name}`,token,r.name)}>下载</Button></td></tr>)}</tbody></table></div>:<Empty title="还没有产物" description="执行或生成后，日志、截图、Markdown、脚本与报告会保存到私有对象存储。"/>;}
export function Preview({artifact,base,token,onClose}){const [content,setContent]=useState(''),[url,setUrl]=useState(''),[error,setError]=useState('');useEffect(()=>{let active=true,object;request(`${base}/artifacts/${artifact.taskId}/${artifact.name}`,token,{raw:true}).then(async blob=>{if(!active)return;if(artifact.name.endsWith('.png')){object=URL.createObjectURL(new Blob([blob],{type:'image/png'}));setUrl(object);}else setContent(await blob.text());}).catch(e=>setError(e.message));return()=>{active=false;if(object)URL.revokeObjectURL(object);};},[artifact,base,token]);return <Drawer title={artifact.name} subtitle="PRIVATE OBJECT STORAGE" onClose={onClose} wide><ErrorNotice error={error}/>{url?<img className="screenshot" src={url} alt="执行截图"/>:artifact.name.endsWith('.md')?<MarkdownView text={content}/>:<Code value={content} label={artifact.name}/>}</Drawer>;}
