import React,{useState} from 'react';
import {Header,Metrics,Panel,Button,Badge,Tag,Tabs,Search,Drawer,Code,Empty,Icon,useResource,ErrorNotice,ExecutionTable,ArtifactList,Preview,StatBar} from './common.jsx';
import {request,short,formatTime} from './api.js';
import {RunDetail} from './AutomationViews.jsx';
export function ModelViews({route,token,notify,navigate}){
 const consoleData=useResource('/api/model-console/console',token,8000),audits=useResource('/api/model-console/requests',token,5000);
 const [search,setSearch]=useState(''),[prompt,setPrompt]=useState('Generate a concise test strategy for a task creation API.'),[answer,setAnswer]=useState(null),[busy,setBusy]=useState(false),[detail,setDetail]=useState(null);
 const rows=audits.data||[],provider=consoleData.data?.provider,metrics=consoleData.data?.metrics||{};
 const filtered=rows.filter(r=>(r.id+' '+r.title).toLowerCase().includes(search.toLowerCase()));
 async function testCall(){setBusy(true);try{setAnswer(await request('/api/model/chat/completions',token,{method:'POST',body:{model:provider?.model,messages:[{role:'user',content:prompt}],max_tokens:800,stream:false}}));audits.refresh();consoleData.refresh();notify('请求完成，诊断记录已写入');}catch(e){notify(e.message);}finally{setBusy(false);}}
 async function open(id){try{setDetail(await request('/api/model-console/console/requests/'+id,token));}catch(e){notify(e.message);}}
 const auditTable=list=>list.length?<div className="table-wrap"><table><thead><tr><th>请求 ID / 能力</th><th>状态</th><th>耗时</th><th>模式</th><th>请求时间</th><th/></tr></thead><tbody>{list.map(r=><tr key={r.id} className="clickable" onClick={()=>open(r.id)}><td><div className="title-cell"><span className="row-icon purple"><Icon name="git"/></span><div><strong>{r.title?.startsWith('Run ')?'Chat completion':r.title}</strong><small>{short(r.id)}</small></div></div></td><td><Badge value={r.status}>{r.status==='SUCCEEDED'?'调用成功':undefined}</Badge></td><td className="mono">{r.durationMs} ms</td><td><Tag>{r.result?.mode||'—'}</Tag></td><td>{formatTime(r.createdAt)}</td><td><Icon name="chevron" size={14}/></td></tr>)}</tbody></table></div>:<Empty title="还没有模型请求" description="在 Playground 发起一次请求，或从 AI-SDLC 运行能力。"/>;
 return <><Header eyebrow="MODEL GATEWAY / OPERATIONS" title={route==='providers'?'Provider 与模型':route==='requests'?'请求诊断':route==='playground'?'模型 Playground':'模型服务概览'} description="统一接入模型，掌握每次请求的状态、延迟和调用来源。"><Button icon="refresh" onClick={()=>{consoleData.refresh();audits.refresh();}}>刷新</Button><Button primary icon="play" onClick={()=>navigate('playground')}>测试模型</Button></Header><ErrorNotice error={consoleData.error||audits.error}/>
 {route==='overview'&&<><Metrics items={[{label:'请求总数',value:metrics.total,icon:'activity',note:'当前账户最近 50 条范围'},{label:'成功率',value:metrics.total?`${metrics.successRate}%`:'—',icon:'shield',positive:true,note:'已结束请求统计'},{label:'平均耗时',value:rows.length?Math.round(rows.reduce((n,r)=>n+r.durationMs,0)/rows.length):'—',unit:'ms',icon:'clock',note:'包含网关调用与诊断'},{label:'活跃模型',value:provider?1:0,icon:'layers',note:provider?.model||'等待连接'}]}/><div className="two-column"><Panel title="最近请求" description="请求内容只保存摘要，凭据不会进入日志" actions={<Button quiet onClick={()=>navigate('requests')}>查看全部 →</Button>}>{auditTable(rows.slice(0,6))}</Panel><Panel title="当前模型路由" description="服务端配置，统一权限边界"><div className="panel-body"><div className="connection-top"><div className="connection-icon"><Icon name="spark" size={24}/></div><div><h3>{provider?.name||'—'}</h3><small>{provider?.model}</small></div></div><div className="summary-row"><span>运行模式</span><Badge tone={provider?.mode==='mock'?'amber':'green'}>{provider?.mode||'—'}</Badge></div><div className="summary-row"><span>请求超时</span><b>{provider?.timeoutSeconds||0} 秒</b></div><div className="summary-row"><span>最大并发</span><b>{provider?.maxConcurrency||0}</b></div><div className="summary-row"><span>接口能力</span><span><Tag>JSON</Tag><Tag>SSE</Tag></span></div><div style={{marginTop:20}}><Button icon="arrow" onClick={()=>navigate('providers')}>查看 Provider</Button></div></div></Panel></div></>}
 {route==='providers'&&<><div className="notice"><Icon name="shield"/>密钥仅在服务端环境配置。控制台展示配置状态，不读取或回显原始密钥。</div><div className="console-grid"><div className="connection"><div className="connection-top"><div className="connection-icon"><Icon name="spark" size={25}/></div><div><h3>{provider?.name||'Provider'}</h3><small>OpenAI-compatible API</small></div><Badge tone={provider?.mode==='mock'?'amber':'green'}>{provider?.mode||'—'}</Badge></div><dl>{[['模型',provider?.model],['Endpoint',provider?.endpoint],['凭据状态',provider?.credentialConfigured?'已配置':'未配置 · 当前使用 Mock'],['超时',`${provider?.timeoutSeconds||0} 秒`],['并发上限',provider?.maxConcurrency],['路由','primary / 单 Provider']].map(([k,v])=><div key={k}><dt>{k}</dt><dd className="mono">{v||'—'}</dd></div>)}</dl><div style={{marginTop:18}}><Button primary icon="play" onClick={()=>navigate('playground')}>测试连接与输出</Button></div></div><Panel title="能力与调用契约"><div className="panel-body">{[['对话与流式转发','/v1/chat/completions'],['结构化用例计划','/v1/plans'],['AI CR / 用例 / 编译','/v1/capabilities'],['允许列表','只允许服务端配置模型'],['重试边界','非流式有限重试，流式不静默重放']].map(([k,v])=><div className="summary-row" key={k}><span>{k}</span><code style={{fontSize:10}}>{v}</code></div>)}</div></Panel></div></>}
 {route==='requests'&&<Panel title="全部请求" description="模型请求与 AI-SDLC 能力任务可通过 requestId 关联"><div className="toolbar"><Tag>{rows.length} requests</Tag><Search value={search} onChange={setSearch}/></div>{auditTable(filtered)}</Panel>}
 {route==='playground'&&<div className="input-output"><Panel title="请求输入" description="调用真实网关，不在前端伪造响应"><div className="panel-body"><label className="field">模型<input readOnly value={provider?.model||''}/></label><label className="field">Prompt<textarea rows={12} value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><Button primary icon="play" loading={busy} onClick={testCall}>发送请求</Button>{provider?.mode==='mock'&&<p className="muted" style={{fontSize:10,lineHeight:1.8,marginTop:14}}>当前 Mock 返回固定结构化示例，用于验证网关链路。</p>}</div></Panel><Panel title="响应结果" description="成功与错误都会保留诊断记录"><div className="panel-body">{answer?<Code label="RESPONSE" value={answer}/>:<Empty title="等待一次模型调用"/>}</div></Panel></div>}
 {detail&&<Drawer title={`Request ${short(detail.id)}`} subtitle="MODEL / REQUEST TRACE" onClose={()=>setDetail(null)}><div className="detail-facts"><div><label>状态</label><Badge value={detail.status}>{detail.status==='SUCCEEDED'?'调用成功':undefined}</Badge></div><div><label>耗时</label><b>{detail.durationMs} ms</b></div><div><label>时间</label><b>{formatTime(detail.createdAt)}</b></div></div><ErrorNotice error={detail.error}/><Code label="SANITIZED INPUT" value={detail.input}/><Code label="OUTCOME / USAGE" value={detail.result||{}}/><div className="notice">未知 usage 不会被当成零成本，Prompt 仅保存 Hash。</div></Drawer>}</>;
}
export function SandboxViews({route,token,notify,navigate}){
 const consoleData=useResource('/api/sandbox/console',token,7000),executions=useResource('/api/sandbox/executions',token,4000),artifacts=useResource('/api/sandbox/artifacts',token,8000);
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('ALL'),[preview,setPreview]=useState(null);
 const data=consoleData.data,metrics=data?.metrics||{},rows=executions.data||[],id=route.startsWith('executions/')?route.split('/')[1]:null;
 const filtered=rows.filter(r=>(filter==='ALL'||r.status===filter)&&(r.id+' '+r.title).toLowerCase().includes(search.toLowerCase()));
 return <><Header eyebrow="SANDBOX GATEWAY / EXECUTION CONTROL" title={route.startsWith('executions')?'执行记录':route==='profiles'?'Runtime Profiles':route==='artifacts'?'执行产物':'执行资源概览'} description="统一管理容器执行、资源约束与生命周期，让每个结果都有完整证据。"><Button icon="refresh" onClick={()=>{consoleData.refresh();executions.refresh();artifacts.refresh();}}>刷新</Button><Button primary icon="arrow" onClick={()=>window.location.assign('/automation/')}>发起自动化执行</Button></Header><ErrorNotice error={consoleData.error||executions.error}/>
 {route==='overview'&&<><Metrics items={[{label:'累计执行',value:metrics.total,icon:'box',note:'当前账户最近 50 条范围'},{label:'运行中 / 排队',value:`${metrics.running||0} / ${metrics.queued||0}`,icon:'activity',note:'单实例有界调度'},{label:'执行成功率',value:metrics.total?`${metrics.successRate}%`:'—',icon:'shield',positive:true,note:'已结束任务统计'},{label:'已回收容器',value:rows.filter(r=>r.cleanupStatus==='DESTROYED').length,icon:'check',note:'执行结果与清理状态独立'}]}/><div className="two-column"><Panel title="最近执行" description="Execution、Attempt、报告和清理一目了然" actions={<Button quiet onClick={()=>navigate('executions')}>查看全部 →</Button>}><ExecutionTable rows={rows.slice(0,6)} onOpen={id=>navigate('executions/'+id)} showChannel/></Panel><Panel title="运行时约束" description="Profile 由服务端注册"><div className="panel-body">{[['执行引擎','Docker Engine'],['Runtime','Playwright / Node.js'],['CPU 限制','1 core'],['单任务内存',`${data?.profiles?.[0]?.memoryMb||'—'} MiB`],['文件系统','只读 / 临时工作目录'],['凭据','任务容器不持有云密钥']].map(([k,v])=><div className="summary-row" key={k}><span>{k}</span><b>{v}</b></div>)}</div></Panel></div></>}
 {route.startsWith('executions')&&<Panel title="执行历史" description="支持查看断言、失败原因、输入、日志与截图"><div className="toolbar"><Search value={search} onChange={setSearch}/><select className="filter-select" aria-label="状态筛选" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">全部状态</option><option value="SUCCEEDED">执行通过</option><option value="FAILED">执行失败</option><option value="RUNNING">执行中</option></select></div><ExecutionTable rows={filtered} onOpen={id=>navigate('executions/'+id)}/></Panel>}
 {route==='profiles'&&<><div className="console-grid">{data?.profiles?.map(p=><div className="connection" key={p.id}><div className="connection-top"><div className="connection-icon"><Icon name={p.id==='api-test'?'api':'globe'} size={25}/></div><div><h3>{p.name}</h3><small>{p.id}</small></div><Badge tone="green">已注册</Badge></div><dl>{[['镜像',p.image],['CPU',`${p.cpu} core`],['内存',`${p.memoryMb} MiB`],['超时上限',`${p.timeoutSeconds} 秒`],['网络策略',p.network],['任务身份','非 root / capabilities dropped']].map(([k,v])=><div key={k}><dt>{k}</dt><dd className="mono">{v}</dd></div>)}</dl></div>)}</div><div className="notice" style={{marginTop:20}}><Icon name="shield"/>调用方只能选择已注册 Workload。容器不接收任意宿主挂载或 Docker socket。外部目标需由部署者注册 Profile。</div></>}
 {route==='artifacts'&&<Panel title="Runner 日志与截图" description={`${data?.storage?.bucket||'私有 bucket'} · Supabase Storage`}><ArtifactList rows={artifacts.data||[]} token={token} base="/api/sandbox" onPreview={setPreview}/></Panel>}
 {id&&<RunDetail id={id} token={token} sandbox onClose={()=>navigate('executions')}/>}{preview&&<Preview artifact={preview} base="/api/sandbox" token={token} onClose={()=>setPreview(null)}/>}</>;
}
