import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {APP} from './app-config.js';
import {Icon,Button,ErrorNotice} from './common.jsx';
import {request} from './api.js';
import {StudioViews} from './StudioViews.jsx';
import {AutomationViews} from './AutomationViews.jsx';
import {ModelViews,SandboxViews} from './GatewayViews.jsx';
import './style.css';
const config=window.APP_CONFIG||{};
const supabase=config.supabaseUrl&&config.supabaseAnonKey?createClient(config.supabaseUrl,config.supabaseAnonKey,{auth:{storage:window.sessionStorage,persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}}):null;
const platforms=[{id:'studio',name:'AI-SDLC',hint:'DESIGN & GENERATE',path:'/',icon:'spark'},{id:'automation',name:'Automation',hint:'EXECUTE & OBSERVE',path:'/automation/',icon:'case'},{id:'model',name:'Model Gateway',hint:'MODEL OPERATIONS',path:'/models/',icon:'git'},{id:'sandbox',name:'Sandbox Gateway',hint:'EXECUTION CONTROL',path:'/sandbox/',icon:'box'}];
const menus={studio:[['overview','工作区概览','grid'],['ai-cr','AI Code Review','shield'],['case-generation','测试用例生成','file'],['case-compile','自动化编译','code'],['runs','任务记录','activity'],['artifacts','材料与产物','cloud']],automation:[['overview','运行概览','grid'],['cases','用例管理','case'],['runs','执行记录','activity'],['artifacts','产物与存储','cloud']],model:[['overview','服务概览','grid'],['providers','Provider 与模型','layers'],['requests','请求诊断','activity'],['playground','Playground','terminal']],sandbox:[['overview','运行概览','grid'],['executions','执行记录','activity'],['profiles','Runtime Profiles','box'],['artifacts','日志与产物','cloud']]};
function App(){const [token,setToken]=useState(sessionStorage.getItem('sdlc-token')||''),[mode,setMode]=useState(sessionStorage.getItem('sdlc-auth-mode')||'supabase'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[operator,setOperator]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[route,setRoute]=useState(location.hash.replace(/^#\/?/,'')||'overview');
 const [identity,setIdentity]=useState(sessionStorage.getItem('sdlc-identity')||'Workspace member');
 const platform=platforms.find(p=>p.id===APP.kind);const title=menus[APP.kind].find(m=>route.startsWith(m[0]))?.[1]||'详情';
 useEffect(()=>{const changed=()=>setRoute(location.hash.replace(/^#\/?/,'')||'overview');window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed);},[]);
 const remember=(value,kind,name)=>{sessionStorage.setItem('sdlc-token',value);sessionStorage.setItem('sdlc-auth-mode',kind);if(name){sessionStorage.setItem('sdlc-identity',name);setIdentity(name);}setToken(value);setMode(kind);};
 useEffect(()=>{if(!supabase)return;const {data}=supabase.auth.onAuthStateChange((_event,session)=>{if(session)remember(session.access_token,'supabase',session.user.email);});return()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);},[toast]);
 function navigate(value){location.hash='/'+value;}
 async function login(event){event.preventDefault();setBusy(true);setError('');try{if(mode==='supabase'){if(!supabase)throw new Error('Supabase 登录尚未配置，请使用 Operator Token');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;remember(data.session.access_token,'supabase',email);}else{const path=APP.kind==='model'?'/api/model/models':APP.kind==='sandbox'?'/api/sandbox/executions':'/api/automation/runs';await request(path,operator);remember(operator,'operator','Private operator');}setPassword('');setOperator('');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function logout(){if(supabase&&mode==='supabase')await supabase.auth.signOut();for(const key of ['sdlc-token','sdlc-auth-mode','sdlc-identity'])sessionStorage.removeItem(key);setToken('');}
 const brand=<div className="brand"><span className="brand-mark"><Icon name="layers" size={24}/></span><div><b>Quality Studio</b><small>ENGINEERING WORKSPACE</small></div></div>;
 if(!token)return <div className="login-shell"><section className="login-art">{brand}<div className="eyebrow">AI-POWERED QUALITY ENGINEERING</div><h1>让每次交付，<br/><span>都有可靠的证据。</span></h1><p>从需求与代码，到可执行的 Web / API 测试。<br/>一个连接模型、自动化与执行环境的质量工作区。</p><div className="login-flow"><span>需求</span><Icon name="arrow" size={14}/><span>用例</span><Icon name="arrow" size={14}/><span>执行</span><Icon name="arrow" size={14}/><span>证据</span></div></section><section className="login-panel"><form className="login-form" onSubmit={login}><span className="eyebrow">WELCOME TO {APP.name.toUpperCase()}</span><h2>登录你的工作区</h2><p>使用 Supabase 账号或部署者提供的访问凭据。</p><ErrorNotice error={error}/><label className="field">登录方式<select value={mode} onChange={e=>setMode(e.target.value)}><option value="supabase" disabled={!supabase}>Supabase 账号</option><option value="operator">Operator Token</option></select></label>{mode==='supabase'?<><label className="field">邮箱<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><label className="field">密码<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="输入你的密码" required/></label></>:<label className="field">访问凭据<input type="password" autoComplete="off" value={operator} onChange={e=>setOperator(e.target.value)} required/></label>}<Button primary loading={busy} icon="arrow" type="submit">进入工作台</Button><div className="login-note">私有工作区 · 凭据仅保存在当前浏览器会话<br/>服务密钥与模型密钥不会发送到浏览器。</div></form></section></div>;
 const props={route,token,notify:setToast,navigate};
 return <div className="shell"><aside className="sidebar">{brand}<div className="platform-picker"><span className="platform-glyph"><Icon name={platform.icon}/></span><div><small>{platform.hint}</small><select aria-label="切换平台" value={APP.kind} onChange={e=>location.assign(platforms.find(p=>p.id===e.target.value).path)}>{platforms.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></div><div className="nav-caption">Workspace</div><nav aria-label={APP.name+' 导航'}>{menus[APP.kind].map(([id,label,icon])=><a key={id} href={'#/'+id} className={`nav-link ${route.startsWith(id)?'active':''}`} title={label}><Icon name={icon} size={18}/><span>{label}</span></a>)}</nav><div className="sidebar-bottom"><div className="nav-caption">Connected platforms</div><div className="platform-links">{platforms.map(p=><a key={p.id} title={p.name} href={p.path}><Icon name={p.icon} size={15}/></a>)}</div><a className="nav-link" href={`https://github.com/SimonL777/${{studio:'ai-sdlc',automation:'automation-platform',model:'model-gateway',sandbox:'sandbox-gateway'}[APP.kind]}`} target="_blank" rel="noreferrer"><Icon name="code"/><span>项目源码</span></a><div className="profile"><span className="avatar">{identity.slice(0,2).toUpperCase()}</span><div><b>{identity.split('@')[0]}</b><small>{mode==='supabase'?'SUPABASE ACCOUNT':'PRIVATE OPERATOR'}</small></div><button aria-label="退出登录" title="退出登录" onClick={logout}><Icon name="logout" size={16}/></button></div></div></aside><main className="workspace"><div className="topbar"><div className="breadcrumb"><Icon name={platform.icon} size={16}/><span>{APP.name}</span><Icon name="chevron" size={11}/><b>{title}</b></div><div className="topbar-right"><span className="environment"><i/>Connected workspace</span><span className="version">v0.2</span><span className="avatar" style={{width:29,height:29,fontSize:10}}>{identity.slice(0,2).toUpperCase()}</span></div></div><div className="page">{APP.kind==='studio'?<StudioViews {...props}/>:APP.kind==='automation'?<AutomationViews {...props}/>:APP.kind==='model'?<ModelViews {...props}/>:<SandboxViews {...props}/>}<div className="footer"><span>Quality Studio · Open-source engineering workspace</span><span>模型模式与执行结果以实际记录为准</span></div></div></main>{toast&&<div role="status" className="toast">{toast}</div>}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
