import React,{useState,useEffect} from 'react';
import {Header,Metrics,Panel,Button,Badge,Tag,Tabs,Search,Drawer,Code,Empty,Icon,MarkdownView,useResource,ErrorNotice,Preview,ArtifactList} from './common.jsx';
import {request,newId,short,formatTime,terminal} from './api.js';
const BASE='/api/automation';
const SAMPLE_MD='# Northstar · 任务与商品服务\n\n## 背景\n团队需要一个轻量任务工作区，并验证商品与购物车接口。\n\n## 验收标准\n1. 用户输入非空标题后可以创建任务，列表显示新任务。\n2. 空标题必须返回 422，页面显示必填提示。\n3. GET /api/products 返回商品数组与总数。\n4. 加入购物车时 total = price × quantity，数量必须为正整数。\n\n## 自动化范围\n覆盖 Web 正向、边界校验，以及 API 状态码与响应字段。';
const SAMPLE_SOURCE='// task-service.js\nexport function createTask(title) {\n  return { status: 201, title };\n}\n';
const CAPS=[{id:'ai-cr',name:'AI Code Review',cn:'需求实现检查',icon:'shield',desc:'基于 DD 的证据驱动检查。对照需求与源码，识别漏实现、错实现和历史影响。',tag:'DEFECT DETECTOR',color:'purple'},{id:'case-generation',name:'测试用例生成',cn:'Markdown → Markdown',icon:'file',desc:'把需求材料转化为结构化测试设计，覆盖正向、边界与异常场景。',tag:'TEST DESIGN',color:'blue'},{id:'case-compile',name:'自动化 Case 编译',cn:'Case → Workflow → Spec',icon:'code',desc:'将可读用例编译为可校验 Workflow，生成可重现的 Web/API 自动化脚本。',tag:'AUTOMATION',color:'green'}];
function CapabilityForm({capability,token,onClose,onCreated}){
 const [title,setTitle]=useState('Northstar · '+CAPS.find(c=>c.id===capability).cn),[markdown,setMarkdown]=useState(SAMPLE_MD),[source,setSource]=useState(capability==='ai-cr'?SAMPLE_SOURCE:''),[baseSource,setBase]=useState(''),[diff,setDiff]=useState(''),[channel,setChannel]=useState('WEB'),[tab,setTab]=useState('requirements'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function upload(e){const f=e.target.files?.[0];if(!f)return;if(f.size>40000){setError('材料请控制在 40 KB 内');return;}setMarkdown(await f.text());setTitle(f.name.replace(/\.md$/,''));}
 async function submit(){setBusy(true);try{const result=await request(`${BASE}/studio/runs`,token,{method:'POST',key:newId(),body:{capability,title,markdown,source,baseSource,diff,channel}});onCreated(result);onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Drawer title={CAPS.find(c=>c.id===capability).name} subtitle="AI-SDLC / NEW TASK" onClose={onClose} wide actions={<><Button onClick={onClose}>取消</Button><Button primary icon="spark" loading={busy} onClick={submit}>开始{capability==='ai-cr'?'检查':capability==='case-generation'?'生成':'编译'}</Button></>}>
 <ErrorNotice error={error}/><div className="form-grid"><label className="field">任务名称<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={160}/></label><label className="field">输出类型<select value={channel} onChange={e=>setChannel(e.target.value)}><option>WEB</option><option>API</option></select></label></div><Tabs value={tab} onChange={setTab} items={[{id:'requirements',label:capability==='case-compile'?'Markdown 用例':'需求材料'},{id:'preview',label:'预览'},...(capability==='ai-cr'?[{id:'source',label:'完整源码'},{id:'base',label:'历史基线 / Diff'}]:[])]}/>
 {tab==='requirements'&&<><label className="dropzone"><Icon name="file" size={15}/> 上传 Markdown 文件，或直接在下方编辑<input className="file-input" type="file" accept=".md,.txt,text/plain,text/markdown" onChange={upload}/></label><label className="field">{capability==='case-compile'?'用例 Markdown（支持嵌入 JSON Workflow）':'PRD / 验收标准'}<textarea rows={19} className="mono" value={markdown} onChange={e=>setMarkdown(e.target.value)} maxLength={30000}/></label></>}
 {tab==='preview'&&<MarkdownView text={markdown}/>}
 {tab==='source'&&<label className="field">Feature 完整源码<textarea rows={20} className="mono" value={source} onChange={e=>setSource(e.target.value)} maxLength={24000}/><small>仅有 Diff 不足以判断完整行为。确认缺陷必须包含可回查的需求与代码证据。</small></label>}
 {tab==='base'&&<><label className="field">Base 完整源码（可选）<textarea rows={9} className="mono" value={baseSource} onChange={e=>setBase(e.target.value)}/></label><label className="field">Code Diff（可选）<textarea rows={9} className="mono" value={diff} onChange={e=>setDiff(e.target.value)}/></label></>}
 <div className="notice warning"><Icon name="alert"/>{capability==='ai-cr'?'缺少基线或完整证据时输出“待补上下文”，不将推测当成缺陷。':'使用当前 Model Gateway。若为 Mock 模式，产出会明确标注为演示样例。'}</div>
 </Drawer>;
}
function StudioDetail({id,token,onClose,onSaved,notify}){
 const resource=useResource(`${BASE}/studio/runs/${id}`,token,2000);const task=resource.data,result=task?.result;const [tab,setTab]=useState('output'),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 async function saveCase(){setBusy(true);try{const c=await request(`${BASE}/cases`,token,{method:'POST',body:{title:task.title,description:`由 AI-SDLC Markdown 编译生成；模型模式 ${result.providerMode}；来源 Run ${task.id}`,workflow:result.workflow,tags:['AI-SDLC',result.providerMode==='mock'?'MOCK':'AI','P1']}});setSaved(true);notify('已保存到自动化用例库');onSaved?.(c);}catch(e){notify(e.message);}finally{setBusy(false);}}
 return <><Drawer title={task?.title||'能力执行详情'} subtitle="AI-SDLC / RUN DETAIL" onClose={onClose} wide actions={<><Button icon="refresh" onClick={resource.refresh}>刷新</Button>{result?.workflow&&<Button primary icon={saved?"arrow":"plus"} loading={busy} onClick={saved?()=>window.location.assign("/automation/#/cases"):saveCase}>{saved?"前往用例库":"保存为自动化用例"}</Button>}<Button onClick={onClose}>关闭</Button></>}><ErrorNotice error={resource.error||task?.error}/>{task&&<><div className="detail-facts"><div><label>状态</label><Badge value={task.status}>{task.status==='SUCCEEDED'?'已完成':undefined}</Badge></div><div><label>模型模式</label><Badge tone={result?.providerMode==='mock'?'amber':'blue'}>{result?.providerMode||'等待结果'}</Badge></div><div><label>创建时间</label><b>{formatTime(task.createdAt)}</b></div></div>{!terminal(task.status)&&<div className="progress"><span className="spinner"/>正在处理材料，结果会自动刷新。</div>}{result?.fixture&&<div className="notice warning"><Icon name="alert"/>Mock 演示产物，不能作为真实代码扫描或需求覆盖结论。</div>}<Tabs value={tab} onChange={setTab} items={[{id:'output',label:'报告 / Markdown'},{id:'structured',label:result?.findings?'检查发现':'结构化结果'},{id:'input',label:'输入材料'},...(result?.spec?[{id:'code',label:'编译脚本'}]:[])]}/><div className="artifact-chips">{result?.artifacts?.map(name=><Button icon="file" key={name} onClick={()=>setPreview({taskId:id,name})}>{name}</Button>)}</div>
 {tab==='output'&&<MarkdownView text={result?.markdown||'正在等待输出…'}/>}
 {tab==='input'&&<><MarkdownView text={task.input?.request?.markdown}/>{task.input?.request?.source&&<Code label="FEATURE SOURCE" value={task.input.request.source}/>}</>}
 {tab==='code'&&<><Code label={`COMPILER / ${result.compilerVersion}`} value={result.spec}/><div className="notice">SHA-256 · {result.specHash?.slice(0,28)}</div></>}
 {tab==='structured'&&(result?.findings?<div className="findings">{result.findings.map((f,i)=><div key={i} className={`finding ${f.conclusion==='confirmed_defect'?'confirmed':''}`}><div className="inline-actions"><Tag>{f.id}</Tag><Tag color="purple">{f.severity}</Tag><Badge value={f.conclusion}/></div><h3>{f.title}</h3><p>{f.domain==='historical_intrusion'?'历史功能影响':'需求实现正确性'} · {f.trigger}</p>{f.requirementEvidence&&<blockquote>需求：{f.requirementEvidence}<br/>源码：{f.codeEvidence}</blockquote>}<p><b>实际：</b>{f.actual}</p><p><b>预期：</b>{f.expected}</p></div>)}</div>:<Code value={result||{}} label="STRUCTURED OUTPUT"/>)}
 </>}</Drawer>{preview&&<Preview artifact={preview} token={token} base={BASE} onClose={()=>setPreview(null)}/>}</>;
}
export function StudioViews({route,token,notify,navigate}){
 const tasks=useResource(`${BASE}/studio/runs`,token,5000),overview=useResource(`${BASE}/overview`,token,10000),artifacts=useResource(`${BASE}/artifacts`,token,8000),model=useResource('/api/model/models',token,15000);
 const [creating,setCreating]=useState(null),[search,setSearch]=useState(''),[preview,setPreview]=useState(null);
 const rows=tasks.data||[],active=route.startsWith('runs/')?route.split('/')[1]:null;
 const capFilter=['ai-cr','case-generation','case-compile'].includes(route)?route:null;
 const filtered=rows.filter(r=>(!capFilter||r.input?.request?.capability===capFilter)&&(r.title+' '+r.id).toLowerCase().includes(search.toLowerCase()));
 const counts=Object.fromEntries(CAPS.map(c=>[c.id,rows.filter(r=>r.input?.request?.capability===c.id).length]));
 const title=route==='overview'?'Quality starts with clarity.':route==='artifacts'?'材料与产物':capFilter?CAPS.find(c=>c.id===capFilter).name:'任务记录';
 function table(items){return items.length?<div className="table-wrap"><table><thead><tr><th>任务名称</th><th>能力</th><th>状态</th><th>模型</th><th>更新时间</th><th/></tr></thead><tbody>{items.map(r=><tr className="clickable" key={r.id} onClick={()=>navigate('runs/'+r.id)}><td><div className="title-cell"><span className="row-icon purple"><Icon name={CAPS.find(c=>c.id===r.input?.request?.capability)?.icon||'spark'}/></span><div><strong>{r.title}</strong><small>{short(r.id)}</small></div></div></td><td><Tag color="purple">{CAPS.find(c=>c.id===r.input?.request?.capability)?.cn||r.kind}</Tag></td><td><Badge value={r.status}>{r.status==='SUCCEEDED'?'已完成':undefined}</Badge></td><td><Tag color={r.result?.providerMode==='mock'?'gray':'blue'}>{r.result?.providerMode||'—'}</Tag></td><td>{formatTime(r.updatedAt)}</td><td><Icon name="chevron" size={14}/></td></tr>)}</tbody></table></div>:<Empty title="开始你的第一个质量任务" description="上传 Markdown 材料，选择 AI CR、用例生成或自动化编译。"><Button primary icon="plus" onClick={()=>setCreating(capFilter||'case-generation')}>新建任务</Button></Empty>;}
 return <><Header eyebrow="AI-SDLC / QUALITY WORKSPACE" title={title} description="连接需求、代码与测试证据，让 AI 参与可验证的研发交付。"><Button icon="refresh" onClick={()=>{tasks.refresh();overview.refresh();artifacts.refresh();}}>刷新</Button><Button primary icon="plus" onClick={()=>setCreating(capFilter||'case-generation')}>新建任务</Button></Header><ErrorNotice error={tasks.error}/>
 {route==='overview'&&<><div className="hero"><div><div className="hero-label">DESIGN → VALIDATE → DELIVER</div><h2>把需求，变成可靠的交付证据。</h2><p>从 Markdown 材料开始，进行需求实现检查、生成测试用例，再编译为可执行自动化。每一步都有输入、版本与结果。</p><div style={{marginTop:17}}><Button primary icon="spark" onClick={()=>setCreating('case-generation')}>从需求开始</Button></div></div><div className="hero-icon"><Icon name="layers" size={100}/></div></div>
 <Metrics items={[{label:'质量任务',value:rows.length,note:'当前工作区累计任务',icon:'layers'},{label:'AI CR 检查',value:counts['ai-cr'],note:'需求实现与历史影响',icon:'shield'},{label:'用例生成',value:counts['case-generation'],note:'Markdown 输入 / 输出',icon:'file'},{label:'自动化编译',value:counts['case-compile'],note:'Workflow + 确定性脚本',icon:'code'}]}/>
 <div className="feature-grid">{CAPS.map(c=><button className="feature" key={c.id} onClick={()=>navigate(c.id)}><span className="feature-icon"><Icon name={c.icon} size={23}/></span><span className="feature-arrow"><Icon name="arrow" size={16}/></span><h3>{c.name}</h3><p>{c.desc}</p><span className="feature-footer"><span>{c.tag}</span><span>{counts[c.id]} 次任务</span></span></button>)}</div>
 <div className="two-column"><Panel title="最近任务" description="从输入材料到输出证据，可完整回溯" actions={<Button quiet icon="arrow" onClick={()=>navigate('runs')}>全部任务</Button>}>{table(rows.slice(0,5))}</Panel><Panel title="工作区连接" description="跨平台的能力与资源"><div className="panel-body"><div className="summary-row"><span>Model Gateway</span><Badge tone={model.data?.mode==='mock'?'amber':'green'}>{model.data?.mode||'待连接'}</Badge></div><div className="summary-row"><span>自动化用例库</span><b>{overview.data?.caseCount||0} 条</b></div><div className="summary-row"><span>对象存储</span><Tag color="green">Supabase Storage</Tag></div><div className="summary-row"><span>支持的用例类型</span><span><Tag color="blue">WEB</Tag><Tag color="purple">API</Tag></span></div><div style={{marginTop:18}}><Button icon="arrow" onClick={()=>window.location.assign('/automation/')}>前往自动化平台</Button></div></div></Panel></div></>}
 {(capFilter||route.startsWith('runs'))&&<>{capFilter&&<div className="notice"><Icon name={CAPS.find(c=>c.id===capFilter).icon}/>{CAPS.find(c=>c.id===capFilter).desc}</div>}<Panel title={capFilter?'能力执行记录':'全部任务'}><div className="toolbar"><span className="muted" style={{fontSize:10}}>{filtered.length} 条任务</span><Search value={search} onChange={setSearch}/></div>{table(filtered)}</Panel></>}
 {route==='artifacts'&&<Panel title="材料与生成产物" description="所有文件通过鉴权访问，存储在私有 bucket"><ArtifactList rows={(artifacts.data||[]).filter(a=>rows.some(r=>r.id===a.taskId))} base={BASE} token={token} onPreview={setPreview}/></Panel>}
 {creating&&<CapabilityForm capability={creating} token={token} onClose={()=>setCreating(null)} onCreated={r=>{tasks.refresh();navigate('runs/'+r.id);notify('任务已进入处理队列');}}/>}
 {active&&<StudioDetail id={active} token={token} onClose={()=>navigate('runs')} notify={notify}/>} {preview&&<Preview artifact={preview} base={BASE} token={token} onClose={()=>setPreview(null)}/>}</>;
}
