import http from 'node:http';
export const html=`<!doctype html><html><head><meta charset="utf-8"><style>body{font:16px system-ui;background:#f3f5f9;color:#17233b;margin:0}header{background:#111b31;color:white;padding:25px 9%}main{max-width:850px;margin:50px auto;background:white;padding:32px;border-radius:16px;box-shadow:0 12px 40px #17233b10}input,button{padding:12px;border-radius:8px;border:1px solid #ddd}button{background:#6558e8;color:white;cursor:pointer}li{padding:12px;border-bottom:1px solid #eee}.products{display:flex;gap:15px}.product{padding:20px;background:#f7f7fd;border-radius:9px}small{color:#8490a5}</style></head><body><header>◈ NORTHSTAR / DEMO COMMERCE</header><main><small>ISOLATED TEST APPLICATION</small><h1>Task workspace</h1><label>Task <input data-testid="title" placeholder="What needs to be done?"></label> <button data-testid="add">Add task</button><p data-testid="error" hidden>Please enter a task title</p><ul data-testid="items"></ul><h2>Product catalog</h2><div class="products" data-testid="products"><div class="product">Mechanical Keyboard · $89</div><div class="product">Studio Headphones · $129</div><div class="product">Desk Lamp · $49</div></div><p data-testid="counter">0 tasks</p></main><script>document.querySelector('[data-testid=add]').onclick=()=>{const input=document.querySelector('input'),error=document.querySelector('[data-testid=error]');if(!input.value.trim()){error.hidden=false;return;}error.hidden=true;const li=document.createElement('li');li.textContent=input.value;document.querySelector('ul').append(li);input.value='';document.querySelector('[data-testid=counter]').textContent=document.querySelectorAll('li').length+' tasks';};</script></body></html>`;
export async function startFixture(){
 const tasks=[],products=[{id:1,name:'Mechanical Keyboard',price:89},{id:2,name:'Studio Headphones',price:129},{id:3,name:'Desk Lamp',price:49}];
 const server=http.createServer(async(req,res)=>{let body='';for await(const chunk of req){body+=chunk;if(body.length>64000){res.writeHead(413);res.end();return;}}
  let data;try{data=body?JSON.parse(body):{};}catch{res.writeHead(400,{'content-type':'application/json'});res.end(JSON.stringify({error:'invalid_json'}));return;}
  const respond=(status,value)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(value));};const path=new URL(req.url,'http://localhost').pathname;
  if(path==='/'){res.writeHead(200,{'content-type':'text/html'});res.end(html);return;}
  if(path==='/api/health')return respond(200,{status:'ok',service:'northstar-demo'});
  if(path==='/api/products'&&req.method==='GET')return respond(200,{items:products,total:products.length});
  if(path==='/api/tasks'&&req.method==='GET')return respond(200,{items:tasks,total:tasks.length});
  if(path==='/api/tasks'&&req.method==='POST'){if(typeof data.title!=='string'||!data.title.trim())return respond(422,{error:'title_required'});const task={id:tasks.length+1,title:data.title,completed:false};tasks.push(task);return respond(201,task);}
  if(path==='/api/cart'&&req.method==='POST'){const product=products.find(p=>p.id===data.productId);if(!product)return respond(404,{error:'product_not_found'});if(!Number.isInteger(data.quantity)||data.quantity<1)return respond(422,{error:'invalid_quantity'});return respond(201,{productId:product.id,quantity:data.quantity,total:product.price*data.quantity});}
  return respond(404,{error:'not_found'});
 });await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return {url:`http://127.0.0.1:${server.address().port}`,close:()=>new Promise(resolve=>server.close(resolve))};
}
